Add explicity check for changed files in PR build job

diff --git a/.github/workflows/pull-request-check.yml b/.github/workflows/pull-request-check.yml
--- a/.github/workflows/pull-request-check.yml
+++ b/.github/workflows/pull-request-check.yml
@@ -11,20 +11,45 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
 
+    - id: changed_files
+      name: Get changed files
+      uses: jitterbit/get-changed-files@v1
+
+    # Determine whether the PR makes _only_ changes to the markdown files in
+    # documentation/decisions: If this is the case, a full build is not
+    # necessary. It will return 'success' if only such .md files where changed
+    # and 'failure' if something else was changed (and a full build should
+    # run).
+    #
+    # Note that it is currently impossible to return early from an actions job
+    # with a successful status, which is why the repeated 'if's in the
+    # subsequent steps are necessary: https://github.com/actions/runner/issues/662
+    - id: only_md_changes
+      name: Check for .md changes
+      run: |
+        for changed_file in ${{ steps.changed_files.outputs.all }}; do
+          if [[ ! "$changed_file" =~ "documentation/decisions/" ]]; then
+            exit 1
+          fi
+        done
+
     - name: Set up JDK 11
       uses: actions/setup-java@v3
+      if: steps.only_md_changes.conclusion == 'failure'
       with:
         distribution: 'adopt'
         java-version: '11'
 
     - name: Cache Maven packages
       uses: actions/cache@v3
+      if: steps.only_md_changes.conclusion == 'failure'
       with:
         path: ~/.m2/repository
         key: maven-${{ hashFiles('**/pom.xml') }}
 
     - name: Cache node and node_modules
       uses: actions/cache@v3
+      if: steps.only_md_changes.conclusion == 'failure'
       with:
         path: |
           documentation/node
@@ -32,6 +57,7 @@ jobs:
         key: node-${{ hashFiles('documentation/package-lock.json') }}
 
     - name: Build
+      if: steps.only_md_changes.conclusion == 'failure'
       run: |
         ./mvnw -B generate-resources -pl documentation -Pantora
         ./mvnw -B clean install -pl esmf-samm-build-plugin
@@ -42,6 +68,7 @@ jobs:
 
     - name: Upload build artifacts
       uses: actions/upload-artifact@v2
+      if: steps.only_md_changes.conclusion == 'failure'
       with:
         name: samm-artifacts
         path: |
